site_name: Sistema Peixe Babel - TCC Engenharia de Computação
site_author: Alex Cyrillo
site_description: Aplicativo para Auxílio no Aprendizado de Idiomas com IA

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

plugins:
  - to-pdf:
      cover: true
      cover_title: "SISTEMA PEIXE BABEL" 
      cover_subtitle: "Aplicativo para Auxílio no Aprendizado de Idiomas com IA - Trabalho de Conclusão de Curso em Engenharia de Computação"
      toc_title: "Sumário"
      cover_logo: "img/logo_universidade.png"
      output_path: pdf/tcc-peixe-babel.pdf
      author: "Alex Cyrillo"
      copyright: "© 2025 Alex Cyrillo. Todos os direitos reservados."
      heading_shift: false
      toc_level: 3


extra_css:
  - css/print.css

nav:
  - Resumo: abstract.md
  - 1. Introdução e Objetivos: chapters/chapter1_introduction.md
  - 2. Requisitos Funcionais e Não Funcionais: chapters/chapter2_requirements.md
  - 3. Modelagens (Funcional, Estática, Dinâmica): chapters/chapter3_modeling.md
  - 4. Estratégias de Implementação:
      - 4.1 Arquitetura e Design: chapters/chapter4_architecture.md
      - 4.2 Implementação: chapters/chapter5_implementation.md
  - 5. Procedimentos de Testes e Validação: chapters/chapter6_testing.md
  - 6. Resultados e Considerações Finais: conclusion.md
  - 7. Referências e Anexos Técnicos: references.md
  - Apêndices:
      - Apêndice A: appendix.md
      - Documento de Visão: documento_de_visao.md
      - Diagrama de Contexto: diagrama_de_contexto.md

# nav:
#   - Início: index.md
#   - Introdução: introducao.md
#   - Documento de Visão: documento_de_visao.md
#   - Diagrama de Contexto: diagrama_de_contexto.md
#   - Requisitos:
#       - Funcionais: requisitos/requisitos_funcionais.md
#       - Não Funcionais: requisitos/requisitos_nao_funcionais.md
#       - Casos de Uso: requisitos/casos_de_uso.md
#   - Arquitetura:
#       - Visão Geral: arquitetura/arquitetura.md
#       - Componentes: arquitetura/componentes.md
#   - Desenvolvimento:
#       - Configuração do Ambiente: desenvolvimento/configuracao_ambiente.md
#       - Guia de Estilo: desenvolvimento/guia_de_estilo.md
#       - Testes: desenvolvimento/testes.md
#   - Referências: referencias.md